---  
lamps:
    - name: "Candy"
      schema:
          - power: False
            transition: 180
            cron: "25 21 * * * 0"
          - power: True
            transition: 60
            cron: "15 1 * * * 0"
          - power: False
            transition: 180
            cron: "45 3 * * * 0"
          - power: True
            transition: 60
            cron: "40 7 * * * 0"
#    - name: "LIFX Flory"
#      schema:
#          - power: True
#            brightness: 0.5
#            saturation: 1.0
#            transition: 60
#            hue: 299
#            cron: "49 19 * * * 0"

